feat: Add FlexibleImpactCards
UCLALibrary/ucla-library-website-components pull request #197
Opened 2022-09-21 20:59 UTC by aprigge

Connected to [APPS-1918](https://jira.library.ucla.edu/browse/APPS-1918)

2022-09-21 21:47 UTC, dianneweinthal requested changes
edits in comments - let me know if you have any questions!

2022-09-21 22:49 UTC, dianneweinthal commented on src/lib-components/ImpactNumberCard.vue
> +}
my bad, we can remove this!

2022-09-22 00:18 UTC, pghorpade approved these changes
👍

2022-09-22 01:21 UTC, dianneweinthal submitted a review, later dismissed
👍

2022-09-22 16:00 UTC, dianneweinthal approved these changes
👍

2022-09-22 16:22 UTC, merged

2022-09-22 16:25 UTC, pghorpade commented
:tada: This PR is included in version 1.56.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ucla-library-website-components/v/1.56.0)
- [GitHub release](https://github.com/UCLALibrary/ucla-library-website-components/releases/tag/v1.56.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: