feat: use rich-text in site alert and spaces, increase alert display time
UCLALibrary/ucla-library-website-components pull request #322
Opened 2023-02-01 00:26 UTC by dianneweinthal

Connected to [APPS-2172](https://jira.library.ucla.edu/browse/APPS-2172)
Connected to [APPS-2169](https://jira.library.ucla.edu/browse/APPS-2169)
Connected to [APPS-2158](https://jira.library.ucla.edu/browse/APPS-2158)

- replaces plain text with rich text for BlockSpaces and SiteNotificationAlert
- increases SiteNotificationAlert display time
- adjusts SiteNotificationAlert styling

2023-02-01 17:46 UTC, sourcefilter approved these changes

2023-02-01 17:49 UTC, sourcefilter requested changes
The alert doesn't seem to be showing: https://deploy-preview-322--ucla-library-storybook.netlify.app/?path=/story/global-sitenotificationalert--long-message

IDK if this is just because the story needs to be updated, even when the message has no rich text content

2023-02-01 21:01 UTC, sourcefilter submitted a review, later dismissed

2023-02-02 00:14 UTC, aprigge approved these changes

2023-02-02 00:16 UTC, merged

2023-02-02 00:19 UTC, pghorpade commented
:tada: This PR is included in version 2.31.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ucla-library-website-components/v/2.31.0)
- [GitHub release](https://github.com/UCLALibrary/ucla-library-website-components/releases/tag/v2.31.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: