feat: APPS-2450 Add multiple block components
UCLALibrary/ucla-library-website-components pull request #409
Opened 2023-10-10 22:42 UTC by tinuola

Connected to [APPS-2450](https://uclalibrary.atlassian.net/browse/APPS-2450)

**Component Created:** 
- BlockCardWithIllustration.vue
- BlockEvent.vue
- BlockSimpleCard.vue
- BlockSpaces.vue
- BlockSponsor.vue

**Stories:** 
- ~/stories/BlockCardWithIllustration.stories.js
- ~/stories/BlockEvent.stories.js
- ~/stories/BlockSimpleCard.stories.js
- ~/stories/BlockSpaces.stories.js
- ~/stories/BlockSponsor.stories.js

**Spec:**
- ~/stories/BlockCardWithIllustration.spec.js
- ~/stories/BlockEvent.spec.js
- ~/stories/BlockSimpleCard.spec.js
- ~/stories/BlockSpaces.spec.js
- ~/stories/BlockSponsor.spec.js

**Checklist:**

-   [x] I checked that it is working locally in the dev server
-   [x] I checked that it is working locally in the storybook
-   [x] I checked that it is working locally in the 
library-website-nuxt dev server
-   [ ] I added a screenshot of it working
-   [ ] UX has reviewed and approved this
-   [x] I assigned this PR to someone on the dev team to review
-   [x] I used a conventional commit message
-   [x] I assigned myself to this PR

2023-10-11 20:51 UTC, pghorpade requested changes

2023-10-11 20:51 UTC, pghorpade commented on src/lib-components/BlockCardWithIllustration.vue
> +      <div v-if="!isHorizontal" class="text">
use v-else vue directive instead of checking for a not condition

2023-10-11 20:51 UTC, pghorpade commented on src/lib-components/BlockEvent.vue
> +      <h2 class="title" v-html="title" />
use v-text https://vuejs.org/api/built-in-directives.html#v-text or mustache template syntax to pass title to h2 element

2023-10-11 20:51 UTC, pghorpade commented on src/lib-components/BlockEvent.vue
> +        <time v-if="startDate" class="dates" v-html="parsedDate" />
use v-text

2023-10-11 20:51 UTC, pghorpade commented on src/lib-components/BlockEvent.vue
> +        <time v-if="parsedTime" class="time" v-html="parsedTime" />
use v-text

2023-10-11 20:51 UTC, pghorpade commented on src/lib-components/BlockSpaces.vue
> +        <h3 v-else class="space-title-no-link" v-html="title" />
use v-text or mustache template syntax

2023-10-11 21:23 UTC, tinuola commented
@pghorpade Changes addressed. Tx.

2023-10-12 01:26 UTC, pghorpade requested changes

2023-10-12 01:26 UTC, pghorpade commented on src/lib-components/BlockSpaces.vue
> +      .svg__graphic-chevron-right {
the fushia stroke is not being applied, use :deep() https://vuejs.org/api/sfc-css-features.html#deep-selectors, in vue3 scoped styles behave differently when updating child component css like svg in this case

2023-10-12 20:12 UTC, pghorpade approved these changes
👍 thanks

2023-10-12 20:21 UTC, merged

2023-10-12 20:24 UTC, pghorpade commented
:tada: This PR is included in version 2.39.0-alpha.12 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/ucla-library-website-components/v/2.39.0-alpha.12)
- [GitHub release](https://github.com/UCLALibrary/ucla-library-website-components/releases/tag/v2.39.0-alpha.12)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-07-12 02:13 UTC, pghorpade commented
:tada: This issue has been resolved in version 3.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ucla-library-website-components/v/3.0.0)
- [GitHub release](https://github.com/UCLALibrary/ucla-library-website-components/releases/tag/v3.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: