fix: APPS-2491 Component updates
UCLALibrary/ucla-library-website-components pull request #417
Opened 2023-11-01 00:32 UTC by tinuola

Connected to [APPS-2491](https://jira.library.ucla.edu/browse/APPS-2491)

**Notes:**
- Removed props from BlockStaffSubjectLibrarian component
- Updated logic to display dismiss icon ('icon-close') in ButtonLink component
- Refactored lingering use of ::v-deep in components
- Addressed linter errors and associated cleanup
- Added App.vue to .gitignore per discussion with @pghorpade 

**Checklist:**

-   [X] I checked that it is working locally in the dev server
-   [X] I checked that it is working locally in the storybook
-   [X] I checked that it is working locally in the 
library-website-nuxt dev server
-   [ ] I added a screenshot of it working
-   [ ] UX has reviewed and approved this
-   [X] I assigned this PR to someone on the dev team to review
-   [X] I used a conventional commit message
-   [X] I assigned myself to this PR

2023-11-03 15:12 UTC, pghorpade approved these changes
💯 thanks for fixing the v-deep to deep

2023-11-03 16:44 UTC, pghorpade requested changes

2023-11-03 16:44 UTC, pghorpade commented on src/lib-components/ButtonLink.vue
> +        case this.iconName === '':
before this add 
Add another case 
to check the linkTarget
case this.linkTarget === '_blank' || this.iconName === 'svg-external-link':
    return 'svg-external-link'

2023-11-03 16:44 UTC, pghorpade commented on src/lib-components/ButtonLink.vue
> +        case this.iconName === '':
remove 
case this.iconName === '':
 return 'none'
 
 make 
default:
return 'none'

2023-11-04 01:25 UTC, tinuola commented
@pghorpade Changes made. Tx.

2023-11-09 06:16 UTC, pghorpade approved these changes
👍  nice work.

2023-11-09 16:59 UTC, merged

2023-11-09 17:01 UTC, pghorpade commented
:tada: This PR is included in version 2.39.0-alpha.17 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/ucla-library-website-components/v/2.39.0-alpha.17)
- [GitHub release](https://github.com/UCLALibrary/ucla-library-website-components/releases/tag/v2.39.0-alpha.17)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-07-12 02:13 UTC, pghorpade commented
:tada: This issue has been resolved in version 3.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ucla-library-website-components/v/3.0.0)
- [GitHub release](https://github.com/UCLALibrary/ucla-library-website-components/releases/tag/v3.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: