feat: APPS-2707 Create FTVA BlockInfo component
UCLALibrary/ucla-library-website-components pull request #529
Opened 2024-06-21 02:32 UTC by tinuola

Connected to [APPS-2707](https://jira.library.ucla.edu/browse/APPS-2707)

**Component Created:** BlockInfo.vue

**Stories:** ~/stories/BlockInfo.stories.js

**Spec:** ~/stories/BlockInfo.spec.js

**Notes:**

{Any notes about what you built. How does it work? Anything missing?}

**Checklist:**

-   [x] I checked that it is working locally in the dev server
-   [x] I checked that it is working locally in the storybook
-   [ ] I checked that it is working locally in the 
library-website-nuxt dev server
-   [ ] I added a screenshot of it working
-   [ ] UX has reviewed and approved this
-   [ ] I assigned this PR to someone on the dev team to review
-   [x] I used a conventional commit message
-   [x] I assigned myself to this PR

2024-06-25 16:24 UTC, farosFreed requested changes
Made some comments

2024-06-25 18:18 UTC, tinuola commented on src/lib-components/BlockInfo.vue
> +    Although this field exists in Craft, the design spec is pending.
Yes, as far as I understand.

2024-06-27 19:34 UTC, farosFreed commented on src/styles/ftva/_block-info.scss
> +.block-info {
needs to be `.ftva.block-info` or theme will have no effect

2024-06-28 16:06 UTC, farosFreed approved these changes
looks good to me

2024-06-28 16:40 UTC, merged

2024-06-28 16:41 UTC, pghorpade commented
:tada: This PR is included in version 2.39.0-alpha.90 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/ucla-library-website-components/v/2.39.0-alpha.90)
- [GitHub release](https://github.com/UCLALibrary/ucla-library-website-components/releases/tag/v2.39.0-alpha.90)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-07-12 02:09 UTC, pghorpade commented
:tada: This issue has been resolved in version 3.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ucla-library-website-components/v/3.0.0)
- [GitHub release](https://github.com/UCLALibrary/ucla-library-website-components/releases/tag/v3.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: