feat: APPS-2799 Create component Block and Section ScreeningDetail
UCLALibrary/ucla-library-website-components pull request #565
Opened 2024-07-15 21:30 UTC by jendiamond

Connected to [APPS-2799](https://jira.library.ucla.edu/browse/APPS-2799)

**Component Created:** {filename}.vue

**Stories:** ~/stories/{filename}.stories.js

**Spec:** ~/stories/{filename}.spec.js

**Notes:**

{Any notes about what you built. How does it work? Anything missing?}

**Checklist:**

-   [ ] I checked that it is working locally in the dev server
-   [ ] I checked that it is working locally in the storybook
-   [ ] I checked that it is working locally in the 
library-website-nuxt dev server
-   [ ] I added a screenshot of it working
-   [ ] UX has reviewed and approved this
-   [ ] I assigned this PR to someone on the dev team to review
-   [ ] I used a conventional commit message
-   [ ] I assigned myself to this PR

2024-07-19 21:10 UTC, farosFreed requested changes
Mostly looks good, left a comment about how to get responsive videoembed

2024-07-19 21:10 UTC, farosFreed commented on src/lib-components/BlockScreeningDetail.vue
> +    <VideoEmbed
The VideoEmbed component is not responsive on its own, it depends on responsiveVideo for the behavior. 
Please see the ReponsiveVideo.stories file for an example of how to slot VideoEmbed into RepsonsiveVideo for responsive behavior

2024-07-23 16:32 UTC, jendiamond reviewed
🍰

2024-07-23 17:04 UTC, farosFreed approved these changes
Looks great!

2024-07-23 17:22 UTC, merged