APPS-2876   fix: Component BlockEventDetail - No map icon If no location
UCLALibrary/ucla-library-website-components pull request #583
Opened 2024-08-07 04:51 UTC by jendiamond

Connected to [APPS-2876](https://jira.library.ucla.edu/browse/APPS-2876)

Previously:
<img width="283" alt="Screenshot 2024-08-06 at 9 50 16 PM" src="https://github.com/user-attachments/assets/14ab9eb1-e564-404a-a266-4df23bb3f314">

**Checklist:**
-   [ ] I checked that it is working locally in the dev server
-   [ ] I checked that it is working locally in the storybook
-   [ ] I checked that it is working locally in the 
library-website-nuxt dev server
-   [ ] I added a screenshot of it working
-   [ ] UX has reviewed and approved this
-   [ ] I assigned this PR to someone on the dev team to review
-   [ ] I used a conventional commit message
-   [ ] I assigned myself to this PR

2024-08-07 22:38 UTC, pghorpade approved these changes
👍

2024-08-08 16:54 UTC, tinuola approved these changes

2024-08-08 16:59 UTC, tinuola requested changes
Remove comment/note about adding Calendar Button.

2024-08-08 18:02 UTC, tinuola approved these changes

2024-08-08 20:39 UTC, merged

2024-08-08 20:41 UTC, pghorpade commented
:tada: This issue has been resolved in version 3.6.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ucla-library-website-components/v/3.6.1)
- [GitHub release](https://github.com/UCLALibrary/ucla-library-website-components/releases/tag/v3.6.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: