feat: APPS-2954 MultiComponent update with DateCreated prop
UCLALibrary/ucla-library-website-components pull request #625
Opened 2024-10-01 21:31 UTC by tinuola

Connected to [APPS-2954](https://jira.library.ucla.edu/browse/APPS-2954)

**Component Updated:** BlockCardWithIllustration.vue, CardMeta.vue, SectionTeaserCard.vue

**Stories:** ~/stories/SectionTeaserCard.stories.js

**Notes:**

{Any notes about what you built. How does it work? Anything missing?}

**Checklist:**

-   [ ] I checked that it is working locally in the dev server
-   [ ] I checked that it is working locally in the storybook
-   [ ] I checked that it is working locally in the 
library-website-nuxt dev server
-   [ ] I added a screenshot of it working
-   [ ] UX has reviewed and approved this
-   [ ] I assigned this PR to someone on the dev team to review
-   [ ] I used a conventional commit message
-   [ ] I assigned myself to this PR

2024-10-01 23:54 UTC, farosFreed requested changes

2024-10-01 23:54 UTC, farosFreed commented on src/styles/ftva/_block-card-with-image.scss
> +                color: #676767;
can we try `color: $subtitle-grey;` ?

2024-10-02 00:04 UTC, tinuola commented on src/styles/ftva/_block-card-with-image.scss
> +                color: #676767;
Sure thing!

2024-10-02 15:31 UTC, farosFreed approved these changes

2024-10-02 15:56 UTC, merged

2024-10-02 15:57 UTC, pghorpade commented
:tada: This PR is included in version 3.26.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ucla-library-website-components/v/3.26.0)
- [GitHub release](https://github.com/UCLALibrary/ucla-library-website-components/releases/tag/v3.26.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: