DRAFT: APPS-2959 FlexibleMediaGallery FTVA variant
UCLALibrary/ucla-library-website-components pull request #626
Opened 2024-10-02 21:27 UTC by tinuola

Connected to [APPS-2959](https://jira.library.ucla.edu/browse/APPS-2959)

**Component Update:**
- ~/Flexible/MediaGallery/BannerImage.vue
- ~/Flexible/MediaGallery.vue
- MediaBadge.vue

**Stories:**
- ~/stories/{filename}.stories.js
- ~/stories/{filename}.stories.js
- ~/stories/{filename}.stories.js

**Notes:**

{Any notes about what you built. How does it work? Anything missing?}

**Checklist:**

-   [ ] I checked that it is working locally in the dev server
-   [ ] I checked that it is working locally in the storybook
-   [ ] I checked that it is working locally in the 
library-website-nuxt dev server
-   [ ] I added a screenshot of it working
-   [ ] UX has reviewed and approved this
-   [ ] I assigned this PR to someone on the dev team to review
-   [x] I used a conventional commit message
-   [x] I assigned myself to this PR

2024-10-04 15:25 UTC, axamei commented
@tinuola the blue icon overlay should be a circle instead of the molecule. that is the only discrepancy with the design that i see

2024-10-07 18:50 UTC, farosFreed requested changes

2024-10-07 18:50 UTC, farosFreed commented on src/lib-components/Flexible/MediaGallery.vue
> +    <section v-if="theme && fullWidthGallery" class="gallery-header">
can we be more explicit here and specify theme.value = ftva? Especially if there are ftva styles that this depends on

2024-10-07 18:50 UTC, farosFreed commented on src/lib-components/Flexible/MediaGallery/BannerImage.vue
> +        <span v-if="theme">
same comment as before, can we specify theme.value === ftva? Or add a class to this space and use display:none to hide it on the default.scss theme file

2024-10-07 18:50 UTC, farosFreed commented on src/lib-components/Flexible/MediaGallery/BannerImage.vue
> +        <SvgIconFtvaDropTriangle v-if="theme" class="drop-triangle" :class="{ 'is-expanded': expanded }" />
one more, can we specify theme.value === 'ftva'?

2024-10-08 18:41 UTC, pghorpade approved these changes
this is comprehensive and well thought out PR. 💯

2024-10-08 18:53 UTC, merged

2024-10-08 18:55 UTC, pghorpade commented
:tada: This PR is included in version 3.28.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ucla-library-website-components/v/3.28.0)
- [GitHub release](https://github.com/UCLALibrary/ucla-library-website-components/releases/tag/v3.28.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: